import React from 'react';
import { 
  Apple, 
  Banana, 
  Beef, 
  Beer, 
  Cake, 
  Candy, 
  Carrot, 
  Cherry, 
  Citrus, 
  Coffee, 
  Cookie, 
  Croissant, 
  Dessert, 
  Donut, 
  Egg, 
  Fish, 
  Grape, 
  Ham, 
  IceCream, 
  Leaf, 
  Milk, 
  Nut, 
  Pizza, 
  Popcorn, 
  Salad, 
  Sandwich, 
  Soup, 
  Sprout, 
  Utensils, 
  Wheat, 
  Wine,
  Droplets,
  Flame,
  Shell,
  Shrimp,
  GlassWater,
  Bean,
  Circle,
  Square,
  Cylinder,
  Drumstick,
  Beef as Meat,
  Milk as Bottle,
  LucideIcon
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  'огурцы': Leaf,
  'рыба': Fish,
  'картофель': Circle,
  'зелень': Leaf,
  'говядина': Meat,
  'курица': Drumstick,
  'куриное филе': Drumstick,
  'свекла': Circle,
  'молоко': Bottle,
  'соль': Circle,
  'морковь': Carrot,
  'яйца': Egg,
  'помидоры': Apple,
  'чеснок': Nut,
  'мука': Wheat,
  'масло': Square,
  'сыр': Square,
  'лук': Nut,
  'сахар': Circle,
  'вода': GlassWater,
  'перец': Flame,
  'сметана': Bottle,
  'майонез': Bottle,
  'укроп': Leaf,
  'петрушка': Leaf,
  'лимон': Citrus,
  'грибы': Sprout,
  'рис': Wheat,
  'макароны': Wheat,
  'хлеб': Croissant,
  'мед': Candy,
  'орехи': Nut,
  'яблоки': Apple,
  'груши': Apple,
  'бананы': Banana,
  'клубника': Cherry,
  'малина': Grape,
  'черника': Grape,
  'виноград': Grape,
  'апельсины': Citrus,
  'мандарины': Citrus,
  'киви': Citrus,
  'ананас': Citrus,
  'персик': Apple,
  'абрикос': Apple,
  'слива': Grape,
  'вишня': Cherry,
  'черешня': Cherry,
  'арбуз': Apple,
  'дыня': Apple,
  'тыква': Apple,
  'кабачок': Leaf,
  'баклажан': Leaf,
  'капуста': Leaf,
  'брокколи': Leaf,
  'цветная капуста': Leaf,
  'шпинат': Leaf,
  'салат': Salad,
  'редис': Sprout,
  'горох': Bean,
  'фасоль': Bean,
  'кукуруза': Wheat,
  'перец болгарский': Apple,
  'острый перец': Flame,
  'имбирь': Sprout,
  'корица': Wheat,
  'ваниль': IceCream,
  'какао': Dessert,
  'шоколад': Dessert,
  'кофе': Coffee,
  'чай': Coffee,
  'вино': Wine,
  'пиво': Beer,
  'сок': GlassWater,
  'масло растительное': Bottle,
  'оливковое масло': Bottle,
  'уксус': Bottle,
  'соевый соус': Bottle,
  'горчица': Bottle,
  'хрен': Sprout,
  'кетчуп': Bottle,
  'томатная паста': Bottle,
  'творог': Soup,
  'кефир': Bottle,
  'йогурт': IceCream,
  'сливки': Bottle,
  'мороженое': IceCream,
  'колбаса': Ham,
  'сосиски': Ham,
  'ветчина': Ham,
  'бекон': Ham,
  'фарш': Meat,
  'креветки': Shrimp,
  'краб': Shell,
  'мидии': Shell,
  'кальмары': Fish,
  'осьминог': Fish,
};

interface IngredientIconProps {
  name: string;
  className?: string;
}

export const IngredientIcon: React.FC<IngredientIconProps> = ({ name, className }) => {
  const lowerName = name.toLowerCase();
  
  // Find the best match
  const match = Object.entries(ICON_MAP).find(([key]) => 
    lowerName.includes(key) || key.includes(lowerName)
  );

  const IconComponent = match ? match[1] : Utensils;

  return <IconComponent className={className} />;
};

export default IngredientIcon;
